export const SERVICE_CREATED_SUCCESSFULLY = "App/SERVICE_CREATED_SUCCESSFULLY";
export const SET_SOURCE_LOCATION = "App/SET_SOURCE_LOCATION";
export const SET_DESTINATION_LOCATION = "App/SET_DESTINATION_LOCATION";
export const SET_DISTANCE = "App/SET_DISTANCE";